---
- name: Check if file exists
  stat:
    path={{ jupyterhub_ldap_k8s_file }}
  register: ldap_file

- name: If file exists delete it
  file:
    path={{ jupyterhub_ldap_k8s_file }}
    state=absent
  when: "{{ ldap_file }}"

- name: Deploy template in place
  template:
    src=ldap.yaml.j2
    dest={{ jupyterhub_ldap_k8s_file }}

- name: install_ldap.yml
  raw: "kubectl create -f {{ jupyterhub_ldap_k8s_file }}"
  when: "{{ not delete_ldap }}"
  # if the services are already running avoid the error
  ignore_errors: true

# Delete the file
- name: delete_ldap.yml
  raw: "kubectl delete -f {{ jupyterhub_ldap_k8s_file }}"
  when: "{{ delete_ldap }}"
  # if the services are already running avoid the error
  ignore_errors: true

- name: when deleteing the service, clean the file
  file:
    path={{ jupyterhub_ldap_k8s_file }}
    state=absent
  when: "{{ delete_ldap }}"
